version: "2"

formatters:
  enable:
    - goimports
    - gci
    - gofumpt

linters:
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - decorder
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocognit
    - gosec
    - lll
    - makezero
    - misspell
    - nolintlint
    - prealloc
    - revive
    - thelper
    - unconvert
    - wastedassign
  exclusions:
    rules:
      - linters:
          - revive
        text: "exported (type|function|const|method) .* should have comment"
      - linters:
          - revive
        text: "should have a package comment"
      - linters:
          - govet
        text: "declaration of \"err\" shadows"
      - linters:
          - errcheck
        text: "Error return value of"
  settings:
    errcheck:
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      check-blank: true
    govet:
      enable:
        - shadow
    staticcheck:
      # https://staticcheck.io/docs/options#checks
      checks: ["all", "-ST1000"]
    decorder:
      disable-dec-order-check: false
      disable-init-func-first-check: false
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    nolintlint:
      require-explanation: false
      require-specific: true
