version: "2"

formatters:
  enable:
    - goimports
    - gci
    - gofumpt

linters:
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - gocognit
    - decorder
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - funlen
    - goconst
    - gosec
    - lll
    - misspell
    - revive
    - unconvert
    - gosec
  exclusions:
    rules:
      - linters:
          - revive
        text: "exported (type|function|const|method) .* should have comment"
      - linters:
          - revive
        text: "should have a package comment"
      - linters:
          - govet
        text: "declaration of \"err\" shadows"
  settings:
    errcheck:
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
      check-blank: true
    govet:
      enable:
        - shadow
    staticcheck:
      # https://staticcheck.io/docs/options#checks
      checks: ["all", "-ST1000"]
    decorder:
      disable-dec-order-check: false
      disable-init-func-first-check: false
