// Code generated by themegen. DO NOT EDIT.
// Generated at: 2026-01-31T09:42:02+01:00

package theme

import (
	"image/color"

	termcolor "github.com/mrmarble/termsvg/pkg/color"
)

// builtinThemes is a registry of all built-in themes.
var builtinThemes = map[string]Theme{
	"dracula": Dracula,
	"frappe": Frappe,
	"gruvbox-dark": GruvboxDark,
	"gruvbox-light": GruvboxLight,
	"latte": Latte,
	"macchiato": Macchiato,
	"mocha": Mocha,
	"monokai": Monokai,
	"nord": Nord,
	"solarized-dark": SolarizedDark,
	"solarized-light": SolarizedLight,
}


// Dracula is the "dracula" theme.
var Dracula = Theme{
	Name:       "dracula",
	Foreground: color.RGBA{ R: 248, G: 248, B: 242, A: 255 },
	Background: color.RGBA{ R: 40, G: 42, B: 54, A: 255 },
	Palette:    DraculaPalette,
	WindowBackground: color.RGBA{ R: 40, G: 42, B: 54, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// DraculaPalette is the color palette for the "dracula" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var DraculaPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 33, G: 34, B: 44, A: 255}
	p[1] = color.RGBA{R: 255, G: 85, B: 85, A: 255}
	p[2] = color.RGBA{R: 80, G: 250, B: 123, A: 255}
	p[3] = color.RGBA{R: 241, G: 250, B: 140, A: 255}
	p[4] = color.RGBA{R: 189, G: 147, B: 249, A: 255}
	p[5] = color.RGBA{R: 255, G: 121, B: 198, A: 255}
	p[6] = color.RGBA{R: 139, G: 233, B: 253, A: 255}
	p[7] = color.RGBA{R: 248, G: 248, B: 242, A: 255}
	p[8] = color.RGBA{R: 98, G: 114, B: 164, A: 255}
	p[9] = color.RGBA{R: 255, G: 110, B: 110, A: 255}
	p[10] = color.RGBA{R: 105, G: 255, B: 148, A: 255}
	p[11] = color.RGBA{R: 255, G: 255, B: 165, A: 255}
	p[12] = color.RGBA{R: 214, G: 172, B: 255, A: 255}
	p[13] = color.RGBA{R: 255, G: 146, B: 223, A: 255}
	p[14] = color.RGBA{R: 164, G: 255, B: 255, A: 255}
	p[15] = color.RGBA{R: 255, G: 255, B: 255, A: 255}
	return p
}()

// Frappe is the "frappe" theme.
var Frappe = Theme{
	Name:       "frappe",
	Foreground: color.RGBA{ R: 198, G: 208, B: 245, A: 255 },
	Background: color.RGBA{ R: 48, G: 52, B: 70, A: 255 },
	Palette:    FrappePalette,
	WindowBackground: color.RGBA{ R: 48, G: 52, B: 70, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// FrappePalette is the color palette for the "frappe" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var FrappePalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 81, G: 87, B: 109, A: 255}
	p[1] = color.RGBA{R: 231, G: 130, B: 132, A: 255}
	p[2] = color.RGBA{R: 166, G: 209, B: 137, A: 255}
	p[3] = color.RGBA{R: 229, G: 200, B: 144, A: 255}
	p[4] = color.RGBA{R: 140, G: 170, B: 238, A: 255}
	p[5] = color.RGBA{R: 244, G: 184, B: 228, A: 255}
	p[6] = color.RGBA{R: 129, G: 200, B: 190, A: 255}
	p[7] = color.RGBA{R: 181, G: 191, B: 226, A: 255}
	p[8] = color.RGBA{R: 98, G: 104, B: 128, A: 255}
	p[9] = color.RGBA{R: 231, G: 130, B: 132, A: 255}
	p[10] = color.RGBA{R: 166, G: 209, B: 137, A: 255}
	p[11] = color.RGBA{R: 229, G: 200, B: 144, A: 255}
	p[12] = color.RGBA{R: 140, G: 170, B: 238, A: 255}
	p[13] = color.RGBA{R: 244, G: 184, B: 228, A: 255}
	p[14] = color.RGBA{R: 129, G: 200, B: 190, A: 255}
	p[15] = color.RGBA{R: 165, G: 173, B: 206, A: 255}
	return p
}()

// GruvboxDark is the "gruvbox-dark" theme.
var GruvboxDark = Theme{
	Name:       "gruvbox-dark",
	Foreground: color.RGBA{ R: 235, G: 219, B: 178, A: 255 },
	Background: color.RGBA{ R: 40, G: 40, B: 40, A: 255 },
	Palette:    GruvboxDarkPalette,
	WindowBackground: color.RGBA{ R: 40, G: 40, B: 40, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// GruvboxDarkPalette is the color palette for the "gruvbox-dark" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var GruvboxDarkPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 40, G: 40, B: 40, A: 255}
	p[1] = color.RGBA{R: 204, G: 36, B: 29, A: 255}
	p[2] = color.RGBA{R: 152, G: 151, B: 26, A: 255}
	p[3] = color.RGBA{R: 215, G: 153, B: 33, A: 255}
	p[4] = color.RGBA{R: 69, G: 133, B: 136, A: 255}
	p[5] = color.RGBA{R: 177, G: 98, B: 134, A: 255}
	p[6] = color.RGBA{R: 104, G: 157, B: 106, A: 255}
	p[7] = color.RGBA{R: 168, G: 153, B: 132, A: 255}
	p[8] = color.RGBA{R: 146, G: 131, B: 116, A: 255}
	p[9] = color.RGBA{R: 251, G: 73, B: 52, A: 255}
	p[10] = color.RGBA{R: 184, G: 187, B: 38, A: 255}
	p[11] = color.RGBA{R: 250, G: 189, B: 47, A: 255}
	p[12] = color.RGBA{R: 131, G: 165, B: 152, A: 255}
	p[13] = color.RGBA{R: 211, G: 134, B: 155, A: 255}
	p[14] = color.RGBA{R: 142, G: 192, B: 124, A: 255}
	p[15] = color.RGBA{R: 235, G: 219, B: 178, A: 255}
	return p
}()

// GruvboxLight is the "gruvbox-light" theme.
var GruvboxLight = Theme{
	Name:       "gruvbox-light",
	Foreground: color.RGBA{ R: 60, G: 56, B: 54, A: 255 },
	Background: color.RGBA{ R: 251, G: 241, B: 199, A: 255 },
	Palette:    GruvboxLightPalette,
	WindowBackground: color.RGBA{ R: 251, G: 241, B: 199, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// GruvboxLightPalette is the color palette for the "gruvbox-light" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var GruvboxLightPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 251, G: 241, B: 199, A: 255}
	p[1] = color.RGBA{R: 204, G: 36, B: 29, A: 255}
	p[2] = color.RGBA{R: 152, G: 151, B: 26, A: 255}
	p[3] = color.RGBA{R: 215, G: 153, B: 33, A: 255}
	p[4] = color.RGBA{R: 69, G: 133, B: 136, A: 255}
	p[5] = color.RGBA{R: 177, G: 98, B: 134, A: 255}
	p[6] = color.RGBA{R: 104, G: 157, B: 106, A: 255}
	p[7] = color.RGBA{R: 124, G: 111, B: 100, A: 255}
	p[8] = color.RGBA{R: 146, G: 131, B: 116, A: 255}
	p[9] = color.RGBA{R: 157, G: 0, B: 6, A: 255}
	p[10] = color.RGBA{R: 121, G: 116, B: 14, A: 255}
	p[11] = color.RGBA{R: 181, G: 118, B: 20, A: 255}
	p[12] = color.RGBA{R: 7, G: 102, B: 120, A: 255}
	p[13] = color.RGBA{R: 143, G: 63, B: 113, A: 255}
	p[14] = color.RGBA{R: 66, G: 123, B: 88, A: 255}
	p[15] = color.RGBA{R: 60, G: 56, B: 54, A: 255}
	return p
}()

// Latte is the "latte" theme.
var Latte = Theme{
	Name:       "latte",
	Foreground: color.RGBA{ R: 76, G: 79, B: 105, A: 255 },
	Background: color.RGBA{ R: 239, G: 241, B: 245, A: 255 },
	Palette:    LattePalette,
	WindowBackground: color.RGBA{ R: 239, G: 241, B: 245, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// LattePalette is the color palette for the "latte" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var LattePalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 92, G: 95, B: 119, A: 255}
	p[1] = color.RGBA{R: 210, G: 15, B: 57, A: 255}
	p[2] = color.RGBA{R: 64, G: 160, B: 43, A: 255}
	p[3] = color.RGBA{R: 223, G: 142, B: 29, A: 255}
	p[4] = color.RGBA{R: 30, G: 102, B: 245, A: 255}
	p[5] = color.RGBA{R: 234, G: 118, B: 203, A: 255}
	p[6] = color.RGBA{R: 23, G: 146, B: 153, A: 255}
	p[7] = color.RGBA{R: 172, G: 176, B: 190, A: 255}
	p[8] = color.RGBA{R: 108, G: 111, B: 133, A: 255}
	p[9] = color.RGBA{R: 210, G: 15, B: 57, A: 255}
	p[10] = color.RGBA{R: 64, G: 160, B: 43, A: 255}
	p[11] = color.RGBA{R: 223, G: 142, B: 29, A: 255}
	p[12] = color.RGBA{R: 30, G: 102, B: 245, A: 255}
	p[13] = color.RGBA{R: 234, G: 118, B: 203, A: 255}
	p[14] = color.RGBA{R: 23, G: 146, B: 153, A: 255}
	p[15] = color.RGBA{R: 188, G: 192, B: 204, A: 255}
	return p
}()

// Macchiato is the "macchiato" theme.
var Macchiato = Theme{
	Name:       "macchiato",
	Foreground: color.RGBA{ R: 202, G: 211, B: 245, A: 255 },
	Background: color.RGBA{ R: 36, G: 39, B: 58, A: 255 },
	Palette:    MacchiatoPalette,
	WindowBackground: color.RGBA{ R: 36, G: 39, B: 58, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// MacchiatoPalette is the color palette for the "macchiato" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var MacchiatoPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 73, G: 77, B: 100, A: 255}
	p[1] = color.RGBA{R: 237, G: 135, B: 150, A: 255}
	p[2] = color.RGBA{R: 166, G: 218, B: 149, A: 255}
	p[3] = color.RGBA{R: 238, G: 212, B: 159, A: 255}
	p[4] = color.RGBA{R: 138, G: 173, B: 244, A: 255}
	p[5] = color.RGBA{R: 245, G: 189, B: 230, A: 255}
	p[6] = color.RGBA{R: 139, G: 213, B: 202, A: 255}
	p[7] = color.RGBA{R: 184, G: 192, B: 224, A: 255}
	p[8] = color.RGBA{R: 91, G: 96, B: 120, A: 255}
	p[9] = color.RGBA{R: 237, G: 135, B: 150, A: 255}
	p[10] = color.RGBA{R: 166, G: 218, B: 149, A: 255}
	p[11] = color.RGBA{R: 238, G: 212, B: 159, A: 255}
	p[12] = color.RGBA{R: 138, G: 173, B: 244, A: 255}
	p[13] = color.RGBA{R: 245, G: 189, B: 230, A: 255}
	p[14] = color.RGBA{R: 139, G: 213, B: 202, A: 255}
	p[15] = color.RGBA{R: 165, G: 173, B: 203, A: 255}
	return p
}()

// Mocha is the "mocha" theme.
var Mocha = Theme{
	Name:       "mocha",
	Foreground: color.RGBA{ R: 205, G: 214, B: 244, A: 255 },
	Background: color.RGBA{ R: 30, G: 30, B: 46, A: 255 },
	Palette:    MochaPalette,
	WindowBackground: color.RGBA{ R: 30, G: 30, B: 46, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// MochaPalette is the color palette for the "mocha" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var MochaPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 69, G: 71, B: 90, A: 255}
	p[1] = color.RGBA{R: 243, G: 139, B: 168, A: 255}
	p[2] = color.RGBA{R: 166, G: 227, B: 161, A: 255}
	p[3] = color.RGBA{R: 249, G: 226, B: 175, A: 255}
	p[4] = color.RGBA{R: 137, G: 180, B: 250, A: 255}
	p[5] = color.RGBA{R: 245, G: 194, B: 231, A: 255}
	p[6] = color.RGBA{R: 148, G: 226, B: 213, A: 255}
	p[7] = color.RGBA{R: 186, G: 194, B: 222, A: 255}
	p[8] = color.RGBA{R: 88, G: 91, B: 112, A: 255}
	p[9] = color.RGBA{R: 243, G: 139, B: 168, A: 255}
	p[10] = color.RGBA{R: 166, G: 227, B: 161, A: 255}
	p[11] = color.RGBA{R: 249, G: 226, B: 175, A: 255}
	p[12] = color.RGBA{R: 137, G: 180, B: 250, A: 255}
	p[13] = color.RGBA{R: 245, G: 194, B: 231, A: 255}
	p[14] = color.RGBA{R: 148, G: 226, B: 213, A: 255}
	p[15] = color.RGBA{R: 166, G: 173, B: 200, A: 255}
	return p
}()

// Monokai is the "monokai" theme.
var Monokai = Theme{
	Name:       "monokai",
	Foreground: color.RGBA{ R: 248, G: 248, B: 242, A: 255 },
	Background: color.RGBA{ R: 39, G: 40, B: 34, A: 255 },
	Palette:    MonokaiPalette,
	WindowBackground: color.RGBA{ R: 39, G: 40, B: 34, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// MonokaiPalette is the color palette for the "monokai" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var MonokaiPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 39, G: 40, B: 34, A: 255}
	p[1] = color.RGBA{R: 249, G: 38, B: 114, A: 255}
	p[2] = color.RGBA{R: 166, G: 226, B: 46, A: 255}
	p[3] = color.RGBA{R: 244, G: 191, B: 117, A: 255}
	p[4] = color.RGBA{R: 102, G: 217, B: 239, A: 255}
	p[5] = color.RGBA{R: 174, G: 129, B: 255, A: 255}
	p[6] = color.RGBA{R: 161, G: 239, B: 228, A: 255}
	p[7] = color.RGBA{R: 248, G: 248, B: 242, A: 255}
	p[8] = color.RGBA{R: 117, G: 113, B: 94, A: 255}
	p[9] = color.RGBA{R: 249, G: 38, B: 114, A: 255}
	p[10] = color.RGBA{R: 166, G: 226, B: 46, A: 255}
	p[11] = color.RGBA{R: 244, G: 191, B: 117, A: 255}
	p[12] = color.RGBA{R: 102, G: 217, B: 239, A: 255}
	p[13] = color.RGBA{R: 174, G: 129, B: 255, A: 255}
	p[14] = color.RGBA{R: 161, G: 239, B: 228, A: 255}
	p[15] = color.RGBA{R: 249, G: 248, B: 245, A: 255}
	return p
}()

// Nord is the "nord" theme.
var Nord = Theme{
	Name:       "nord",
	Foreground: color.RGBA{ R: 236, G: 239, B: 244, A: 255 },
	Background: color.RGBA{ R: 46, G: 52, B: 64, A: 255 },
	Palette:    NordPalette,
	WindowBackground: color.RGBA{ R: 46, G: 52, B: 64, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// NordPalette is the color palette for the "nord" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var NordPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 59, G: 66, B: 82, A: 255}
	p[1] = color.RGBA{R: 191, G: 97, B: 106, A: 255}
	p[2] = color.RGBA{R: 163, G: 190, B: 140, A: 255}
	p[3] = color.RGBA{R: 235, G: 203, B: 139, A: 255}
	p[4] = color.RGBA{R: 129, G: 161, B: 193, A: 255}
	p[5] = color.RGBA{R: 180, G: 142, B: 173, A: 255}
	p[6] = color.RGBA{R: 136, G: 192, B: 208, A: 255}
	p[7] = color.RGBA{R: 236, G: 239, B: 244, A: 255}
	p[8] = color.RGBA{R: 76, G: 86, B: 106, A: 255}
	p[9] = color.RGBA{R: 191, G: 97, B: 106, A: 255}
	p[10] = color.RGBA{R: 163, G: 190, B: 140, A: 255}
	p[11] = color.RGBA{R: 235, G: 203, B: 139, A: 255}
	p[12] = color.RGBA{R: 129, G: 161, B: 193, A: 255}
	p[13] = color.RGBA{R: 180, G: 142, B: 173, A: 255}
	p[14] = color.RGBA{R: 136, G: 192, B: 208, A: 255}
	p[15] = color.RGBA{R: 236, G: 239, B: 244, A: 255}
	return p
}()

// SolarizedDark is the "solarized-dark" theme.
var SolarizedDark = Theme{
	Name:       "solarized-dark",
	Foreground: color.RGBA{ R: 131, G: 148, B: 150, A: 255 },
	Background: color.RGBA{ R: 0, G: 43, B: 54, A: 255 },
	Palette:    SolarizedDarkPalette,
	WindowBackground: color.RGBA{ R: 0, G: 43, B: 54, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// SolarizedDarkPalette is the color palette for the "solarized-dark" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var SolarizedDarkPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 7, G: 54, B: 66, A: 255}
	p[1] = color.RGBA{R: 220, G: 50, B: 47, A: 255}
	p[2] = color.RGBA{R: 133, G: 153, B: 0, A: 255}
	p[3] = color.RGBA{R: 181, G: 137, B: 0, A: 255}
	p[4] = color.RGBA{R: 38, G: 139, B: 210, A: 255}
	p[5] = color.RGBA{R: 211, G: 54, B: 130, A: 255}
	p[6] = color.RGBA{R: 42, G: 161, B: 152, A: 255}
	p[7] = color.RGBA{R: 238, G: 232, B: 213, A: 255}
	p[8] = color.RGBA{R: 0, G: 43, B: 54, A: 255}
	p[9] = color.RGBA{R: 203, G: 75, B: 22, A: 255}
	p[10] = color.RGBA{R: 88, G: 110, B: 117, A: 255}
	p[11] = color.RGBA{R: 101, G: 123, B: 131, A: 255}
	p[12] = color.RGBA{R: 131, G: 148, B: 150, A: 255}
	p[13] = color.RGBA{R: 108, G: 113, B: 196, A: 255}
	p[14] = color.RGBA{R: 147, G: 161, B: 161, A: 255}
	p[15] = color.RGBA{R: 253, G: 246, B: 227, A: 255}
	return p
}()

// SolarizedLight is the "solarized-light" theme.
var SolarizedLight = Theme{
	Name:       "solarized-light",
	Foreground: color.RGBA{ R: 101, G: 123, B: 131, A: 255 },
	Background: color.RGBA{ R: 253, G: 246, B: 227, A: 255 },
	Palette:    SolarizedLightPalette,
	WindowBackground: color.RGBA{ R: 253, G: 246, B: 227, A: 255 },
	WindowButtons: [3]color.RGBA{
		{R: 255, G: 95, B: 86, A: 255},  // Close
		{R: 255, G: 189, B: 46, A: 255}, // Minimize
		{R: 24, G: 193, B: 50, A: 255},  // Maximize
	},
}

// SolarizedLightPalette is the color palette for the "solarized-light" theme.
// It extends the standard xterm palette with custom colors for the first 16 ANSI colors.
var SolarizedLightPalette = func() termcolor.Palette {
	p := termcolor.Standard()
	p[0] = color.RGBA{R: 7, G: 54, B: 66, A: 255}
	p[1] = color.RGBA{R: 220, G: 50, B: 47, A: 255}
	p[2] = color.RGBA{R: 133, G: 153, B: 0, A: 255}
	p[3] = color.RGBA{R: 181, G: 137, B: 0, A: 255}
	p[4] = color.RGBA{R: 38, G: 139, B: 210, A: 255}
	p[5] = color.RGBA{R: 211, G: 54, B: 130, A: 255}
	p[6] = color.RGBA{R: 42, G: 161, B: 152, A: 255}
	p[7] = color.RGBA{R: 238, G: 232, B: 213, A: 255}
	p[8] = color.RGBA{R: 0, G: 43, B: 54, A: 255}
	p[9] = color.RGBA{R: 203, G: 75, B: 22, A: 255}
	p[10] = color.RGBA{R: 88, G: 110, B: 117, A: 255}
	p[11] = color.RGBA{R: 101, G: 123, B: 131, A: 255}
	p[12] = color.RGBA{R: 131, G: 148, B: 150, A: 255}
	p[13] = color.RGBA{R: 108, G: 113, B: 196, A: 255}
	p[14] = color.RGBA{R: 147, G: 161, B: 161, A: 255}
	p[15] = color.RGBA{R: 253, G: 246, B: 227, A: 255}
	return p
}()

